### ISSUE TITLE
Could you tell me how to test these models after training?

### ISSUE THREAD

**Issue by benmagnifico** [iamalexkorotin/Wasserstein2Benchmark#1]
Hello iamalexkorotin :-)
I'm an undergraduate student majored in computer science.
Before mentioning what I need, firstly your code was very helpful for me.
I'm working on a problem which is how to solve optimal transport efficiently.
I find that in your notebooks, both train_hd and test_hd containing the training process.
I wonder how can I test the model after training, which is to make the model generate a transport map directly.
And could you show me the test code?
Thanks very much!

**Comment by iamalexkorotin** [comment]
Hi benmagnifico,

**train_** notebooks are designed to prepare the benchmark pairs which will be later used for testing solvers. You do not need to use these notebooks since the pre-trained models for benchmark pairs are already included to the repo and can be easily loaded (see README.MD).

**test_** notebooks contain the code for testing OT solvers. This implies **training** each solver on the prepared benchmark pair and computing the final metrics (L2-UVP, cos), i.e., **testing**. By the design of the benchmark, there is no train/validation/test split. The benchmark pairs are continuous probability distributions and you can sample infinitely many samples from them.

Hope this helps :)

Best wishes,
Alex
